### DISCUSSION TITLE
PerPage Select not rendering correctly?

### DISCUSSION THREAD

**Discussion by MGeurts** [Power-Components/livewire-powergrid#1243] [Q&A] [answered]
The **PerPage select** in the footer is not rendering correctly. It show 2 down arrows.

![Per-Page](https://github.com/Power-Components/livewire-powergrid/assets/5404867/d8be2d24-69d5-4b52-8b18-53283832fc89)

All other items are rendering perfectly.

Does somebody have an idea? Thanks.

**Comment by EmilioVar** [comment]
I have opened an issue about it... I'll give you the solution I found:

The file causing this phenomenon is located in the following path:

/power-components/livewire-powergrid/resources/views/components/frameworks/tailwind/footer.blade.php

To fix it, I removed the element that was repeating

```
<div
                         class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-pg-primary-700 dark:text-pg-primary-300">
                         <x-livewire-powergrid::icons.down class="w-4 h-4" />
                     </div>
```

After that, the element is now displayed correctly.

**Reply by MGeurts** [reply]
Is this already corrected in the latest version 5.1.14?
The issue still exists...

**Reply by EmilioVar** [reply]
The author has answered me and it seems that a configuration must be made

https://github.com/Power-Components/livewire-powergrid/issues/1225

**Reply by thiagoalgo** [reply]
Im using v5.1.16 and problem persist. My workaround is using css:

```css
#power-grid-table-base>div:nth-child(3)>div>div.flex.flex-row.justify-center.md\:justify-start.mb-2.md\:mb-0>div.relative.h-10>div>svg {
    display: none;
}
```
