### DISCUSSION TITLE
I can't change the toggle button colors

### DISCUSSION THREAD

**Discussion by smmodules** [Power-Components/livewire-powergrid#1532] [Themes]
Hi Guys,

I can't change the toggle button colors. I followed the step-by-step instructions for "Creating your Custom Theme" (it doesn't show anything about the toggle button). No matter what I do, my toggle button always has the color as shown in the image below.
I'm using Tailwind Theme.

![2024-05-06 (17)](https://github.com/Power-Components/livewire-powergrid/assets/84677076/6c9cad68-5f48-4f4e-ac37-d5d492475624)

**Comment by dansysanalyst** [comment]
I think you could configure the [presets](http://localhost:5174/get-started/powergrid-configuration.html#presets):

![CleanShot 2024-05-25 at 02 14 11@2x](https://github.com/Power-Components/livewire-powergrid/assets/79267265/5cb4cd3e-8900-4fbc-ae4c-c1aa863caa1a)


```js
    theme: {
      extend: {
        colors: {
                "pg-secondary": colors.red, 
            },
        },
    },
```

or override the classes in your `resources/css/app.css` file.

```css
.bg-pg-secondary-600 {
    --tw-bg-opacity: 1;
    background-color: rgb(235 37 37);
        border-color: rgb(235 37 37);

}
.border-pg-secondary-600 {
    --tw-border-opacity: 1;
    border-color: rgb(235 37 37);
}
```
