### ISSUE TITLE
[Bug]: CSS conflicts with dropdown menu

### ISSUE THREAD

**Issue by marccoadou** [Power-Components/livewire-powergrid#754]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

latest

### Laravel

9+

### Livewire

latest

### Alpine JS

latest

### Theme

Tailwind 3.x

### Describe the bug.

Dropdown classes conflict with each other, thus creating a mess in the css.

### To Reproduce...

The issue arises when you use a class that's named .dropdown and .dropdown-toggle in your own css.
You use the flags important on those classes in your own css.

```css
.dropdown-toggle {
    background: #fff !important;
    padding-left: 10px !important;
    color: #7a7e82 !important
}
```

The way to fix this would be to either let us configure this by publishing the css, prefix your classnames by powergrid, or stop using !important.

### Extra information

```markdown
<?php
 //...
```
